slim:
  domain: kollus-custom-upload-jquery.dev
twig:
  use_twig_cache: false
kollus:
  domain: kollus_domain
  version: 0
  language_key: korean
  service_account:
    key : service_account_key
    api_access_token: api_access_token
    custom_key: custom_key

